bundler_args: --without quality
before_install:
  - gem install bundler --pre
branches:
  only:
    - release-1.2
before_script:
  - mysql -e "create database datamapper_alternate_tests;"
  - mysql -e "create database datamapper_default_tests;"
  - psql  -c "create database datamapper_default_tests;" -U postgres
  - psql  -c "create database datamapper_alternate_tests;" -U postgres
script: "bundle exec rake spec"
rvm:
  - 1.9.3
  - 1.9.2
  - 1.8.7
  - ree
  - 2.0.0
  - ruby-head
  - rbx-19mode
  - rbx-18mode
  - jruby-19mode
  - jruby-18mode
  - jruby-head
env:
  - "GIT_BRANCH=release-1.2 ADAPTER=in_memory PLUGINS=dm-migrations"
  - "GIT_BRANCH=release-1.2 ADAPTER=yaml"

  - "GIT_BRANCH=release-1.2 ADAPTER=sqlite"
  - "GIT_BRANCH=release-1.2 ADAPTER=sqlite PLUGINS=dm-validations"
  - "GIT_BRANCH=release-1.2 ADAPTER=sqlite PLUGINS=dm-constraints"
  - "GIT_BRANCH=release-1.2 ADAPTER=sqlite PLUGINS=dm-validations,dm-constraints"

  - "GIT_BRANCH=release-1.2 ADAPTER=mysql DM_DB_USER=root DM_DB_PASSWORD=''"
  - "GIT_BRANCH=release-1.2 ADAPTER=mysql PLUGINS=dm-validations DM_DB_USER=root DM_DB_PASSWORD=''"
  - "GIT_BRANCH=release-1.2 ADAPTER=mysql PLUGINS=dm-constraints DM_DB_USER=root DM_DB_PASSWORD=''"
  - "GIT_BRANCH=release-1.2 ADAPTER=mysql PLUGINS=dm-validations,dm-constraints DM_DB_USER=root DM_DB_PASSWORD=''"

  - "GIT_BRANCH=release-1.2 ADAPTER=postgres DM_DB_USER=postgres DM_DB_PASSWORD=''"
  - "GIT_BRANCH=release-1.2 ADAPTER=postgres PLUGINS=dm-validations DM_DB_USER=postgres DM_DB_PASSWORD=''"
  - "GIT_BRANCH=release-1.2 ADAPTER=postgres PLUGINS=dm-constraints DM_DB_USER=postgres DM_DB_PASSWORD=''"
  - "GIT_BRANCH=release-1.2 ADAPTER=postgres PLUGINS=dm-validations,dm-constraints DM_DB_USER=postgres DM_DB_PASSWORD=''"
matrix:
  allow_failures:
notifications:
  irc: "irc.freenode.org#datamapper"
